/**
 * SimilarUserService
 *
 * Finds similar users based on feature vectors and recommends quizzes
 * from similar users for intelligent quiz pool reuse.
 *
 * Phase 2: Foundation for similar user discovery
 * Phase 3: FAISS integration for large-scale similarity search
 */

const UserFeatureVectorService = require('./userFeatureVectorService');
const { QuizPool } = require('../models/Quiz');
const User = require('../models/User');

class SimilarUserService {
  /**
   * Find similar users in the system
   *
   * @param {ObjectId} userId - Target user ID to find similar users for
   * @param {Object} options - Search options
   * @returns {Promise<Array>} Array of similar users with metadata
   */
  static async findSimilarUsers(userId, options = {}) {
    const {
      limit = 5,
      minSimilarity = 0.7, // 70% similarity threshold
      excludeUserIds = []
    } = options;

    try {
      // Get target user
      const targetUser = await User.findById(userId);
      if (!targetUser) {
        throw new Error('Target user not found');
      }

      // Generate feature vector for target user
      const targetVector = UserFeatureVectorService.getUserFeatureVector(targetUser);

      // Get all other users (in Phase 3, this will be replaced with FAISS index query)
      const allUsers = await User.find({
        _id: {
          $nin: [userId, ...excludeUserIds]
        }
      }).select('-password'); // Exclude password for security

      // Generate vectors for all users (in Phase 3, vectors will be pre-computed)
      const allVectors = allUsers
        .map(user => {
          try {
            return UserFeatureVectorService.getUserFeatureVector(user);
          } catch (error) {
            console.error(`Error generating vector for user ${user._id}:`, error);
            return null;
          }
        })
        .filter(v => v !== null);

      // Find similar users
      const similarUserVectors = UserFeatureVectorService.findSimilarUsers(
        allVectors,
        targetVector.vector,
        {
          limit,
          minSimilarity,
          excludeUserId: userId
        }
      );

      // Enrich with user details
      const enrichedResults = await Promise.all(
        similarUserVectors.map(async (similarity) => {
          const user = await User.findById(similarity.userId).select('-password');
          return {
            userId: similarity.userId,
            similarity: similarity.similarity,
            similarityPercentage: Math.round(similarity.similarity * 100),
            user: user ? {
              email: user.email,
              profile: user.profile,
              learningPreferences: user.learningPreferences
            } : null,
            matchedDimensions: this._getMatchedDimensions(
              targetVector.vector,
              similarity.metadata
            )
          };
        })
      );

      return enrichedResults;
    } catch (error) {
      console.error('Error finding similar users:', error);
      throw error;
    }
  }

  /**
   * Find quizzes from similar users for a specific topic
   *
   * @param {ObjectId} userId - User requesting quiz recommendations
   * @param {ObjectId} videoId - Video/topic for which to find quizzes
   * @param {Object} options - Search options
   * @returns {Promise<Array>} Recommended quizzes from similar users
   */
  static async findSimilarUserQuizzes(userId, videoId, options = {}) {
    const {
      limit = 3,
      minSimilarity = 0.75, // Higher threshold for quiz reuse
      minQuestionQuality = 6 // Minimum question quality score
    } = options;

    try {
      // Get similar users
      const similarUsers = await this.findSimilarUsers(userId, {
        limit: 10, // Get more similar users to search through
        minSimilarity: 0.65 // Lower threshold for quiz pool search
      });

      // Extract similar user IDs
      const similarUserIds = similarUsers
        .filter(u => u.similarity >= minSimilarity)
        .map(u => u.userId);

      if (similarUserIds.length === 0) {
        return {
          similarUsersFound: 0,
          quizzesFound: 0,
          recommendations: []
        };
      }

      // Find quizzes in QuizPool for the same video generated by similar users
      const similarUserQuizzes = await QuizPool.find({
        originalVideoId: videoId,
        questionQuality: { $gte: minQuestionQuality }
      }).limit(limit);

      // Enrich quiz recommendations with similarity scores
      const recommendations = similarUserQuizzes.map((quiz, index) => {
        // Find the most similar user who attempted this quiz
        const relatedSimilarUser = similarUsers.find(
          u => u.similarity >= minSimilarity
        );

        return {
          quizPoolId: quiz._id,
          microVideoId: quiz.microVideoId,
          microVideoTitle: quiz.microVideoTitle,
          totalQuestions: quiz.totalQuestions,
          questionQuality: quiz.questionQuality,
          difficulty: quiz.difficulty,
          keyPoints: quiz.keyPoints,
          generatedAt: quiz.generatedAt,
          generatedBy: quiz.generatedBy,
          // Recommendation score: combination of question quality and user similarity
          recommendationScore: this._calculateRecommendationScore(
            quiz.questionQuality,
            relatedSimilarUser?.similarity || minSimilarity,
            quiz.createdAt
          ),
          relatedSimilarUser: relatedSimilarUser ? {
            userId: relatedSimilarUser.userId,
            similarityScore: relatedSimilarUser.similarity
          } : null
        };
      });

      // Sort by recommendation score (highest first)
      recommendations.sort((a, b) => b.recommendationScore - a.recommendationScore);

      return {
        similarUsersFound: similarUserIds.length,
        quizzesFound: recommendations.length,
        recommendations: recommendations.slice(0, limit),
        metadata: {
          targetVideoId: videoId,
          minSimilarity,
          minQuestionQuality,
          searchTimestamp: new Date()
        }
      };
    } catch (error) {
      console.error('Error finding similar user quizzes:', error);
      throw error;
    }
  }

  /**
   * Get a batch of similar users for multiple users
   * Useful for building similarity matrices for FAISS initialization
   *
   * @param {Array<ObjectId>} userIds - Array of user IDs to find similar users for
   * @param {Object} options - Search options
   * @returns {Promise<Object>} Similarity relationships map
   */
  static async batchFindSimilarUsers(userIds, options = {}) {
    const {
      limit = 5,
      minSimilarity = 0.7
    } = options;

    const results = {};

    for (const userId of userIds) {
      try {
        results[userId.toString()] = await this.findSimilarUsers(userId, {
          limit,
          minSimilarity
        });
      } catch (error) {
        console.error(`Error finding similar users for ${userId}:`, error);
        results[userId.toString()] = { error: error.message };
      }
    }

    return results;
  }

  /**
   * Recommend next quiz for a user based on similar users' learning path
   *
   * @param {ObjectId} userId - User requesting quiz recommendation
   * @param {Array<ObjectId>} completedVideoIds - Videos user has already completed
   * @returns {Promise<Object>} Recommended next video/quiz
   */
  static async getNextRecommendedQuiz(userId, completedVideoIds = []) {
    try {
      // Get similar users
      const similarUsers = await this.findSimilarUsers(userId, {
        limit: 5,
        minSimilarity: 0.65
      });

      if (similarUsers.length === 0) {
        return {
          success: false,
          message: 'No similar users found for recommendations'
        };
      }

      // Get similar users' completed videos
      const similarUserCompletedVideos = [];
      for (const similarUser of similarUsers) {
        const user = await User.findById(similarUser.userId);
        if (user && user.learningProgress?.selectedTopics) {
          similarUserCompletedVideos.push(...user.learningProgress.selectedTopics);
        }
      }

      // Find videos completed by similar users but not by target user
      const recommendedVideoIds = [...new Set(similarUserCompletedVideos)]
        .filter(videoId => !completedVideoIds.includes(videoId));

      return {
        success: true,
        similarUsersAnalyzed: similarUsers.length,
        recommendedVideoIds: recommendedVideoIds.slice(0, 5),
        metadata: {
          averageSimilarityScore: similarUsers.reduce((sum, u) => sum + u.similarity, 0) / similarUsers.length,
          timestamp: new Date()
        }
      };
    } catch (error) {
      console.error('Error getting next recommended quiz:', error);
      throw error;
    }
  }

  /**
   * Build a similarity index for all users in the system
   * This prepares data for FAISS indexing in Phase 3
   *
   * @returns {Promise<Object>} Similarity index metadata
   */
  static async buildUserSimilarityIndex() {
    try {
      const allUsers = await User.find().select('-password');

      if (allUsers.length === 0) {
        return {
          success: false,
          message: 'No users found',
          usersIndexed: 0
        };
      }

      // Generate feature vectors for all users
      const allVectors = UserFeatureVectorService.batchGenerateVectors(allUsers);

      // Calculate statistics
      const stats = UserFeatureVectorService.getVectorStatistics(allVectors);

      return {
        success: true,
        usersIndexed: allVectors.length,
        totalUsers: allUsers.length,
        vectorDimensions: stats.dimensions,
        vectorStatistics: {
          mean: stats.vectorMean,
          stdDev: stats.vectorStdDev
        },
        indexBuiltAt: new Date(),
        message: 'Similarity index built successfully. Ready for FAISS indexing in Phase 3.'
      };
    } catch (error) {
      console.error('Error building similarity index:', error);
      throw error;
    }
  }

  // ==================== HELPER FUNCTIONS ====================

  /**
   * Calculate which dimensions match between two users
   * @private
   */
  static _getMatchedDimensions(targetVector, metadata) {
    const dimensions = [];

    // Check each dimension for close values (within 0.2 tolerance)
    const tolerance = 0.2;

    // Learning Pace (Dim 0)
    const paceLevelMap = {
      'Slow': 0.33,
      'Moderate': 0.66,
      'Fast': 1.0
    };
    const paceValue = paceLevelMap[metadata.learningPace] || 0.66;
    if (Math.abs(targetVector[0] - paceValue) <= tolerance) {
      dimensions.push('Learning Pace');
    }

    // Problem-Solving Approach (Dim 1)
    const approachMap = {
      'Analytical': 0.33,
      'Practical': 0.66,
      'Creative': 1.0
    };
    const approachValue = approachMap[metadata.problemSolvingApproach] || 0.66;
    if (Math.abs(targetVector[1] - approachValue) <= tolerance) {
      dimensions.push('Problem-Solving Approach');
    }

    // Available Session Time (Dim 2)
    const timeMap = {
      'Micro (5-10 min)': 0.25,
      'Short (15-30 min)': 0.5,
      'Medium (30-60 min)': 0.75,
      'Long (60+ min)': 1.0
    };
    const timeValue = timeMap[metadata.availableSessionTime] || 0.5;
    if (Math.abs(targetVector[2] - timeValue) <= tolerance) {
      dimensions.push('Available Session Time');
    }

    // Learning Focus (Dim 3)
    const focusMap = {
      'Conceptual': 0.2,
      'Practical-Projects': 0.4,
      'Interview-Prep': 0.6,
      'Certification': 0.8,
      'Mixed': 1.0
    };
    const focusValue = focusMap[metadata.learningFocus] || 1.0;
    if (Math.abs(targetVector[3] - focusValue) <= tolerance) {
      dimensions.push('Learning Focus');
    }

    return dimensions;
  }

  /**
   * Calculate recommendation score based on multiple factors
   * @private
   */
  static _calculateRecommendationScore(questionQuality, userSimilarity, createdAt) {
    // Normalize question quality to [0, 1] (out of 10)
    const qualityScore = questionQuality / 10;

    // User similarity is already in [0, 1]
    const similarityScore = userSimilarity;

    // Recency score: prefer more recent quizzes (last 30 days = 1.0, older = lower)
    const daysSinceCreation = (Date.now() - createdAt) / (1000 * 60 * 60 * 24);
    const recencyScore = Math.max(0, 1 - (daysSinceCreation / 30));

    // Weighted combination: quality 50%, similarity 40%, recency 10%
    const recommendationScore =
      (qualityScore * 0.5) +
      (similarityScore * 0.4) +
      (recencyScore * 0.1);

    return Math.round(recommendationScore * 100) / 100; // Round to 2 decimals
  }
}

module.exports = SimilarUserService;
